kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go test
  - go build
  - echo -n "5.2.6,5.2.4" > .tags
  
- name: docker  
  image: plugins/docker
  settings:
    username: kevinbacon
    password: pa55word
    repo: foo/bar
