kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go test
  - go build
  
- name: docker  
  image: plugins/docker
  settings:
    tags: ${DRONE_COMMIT}
    repo: cavs2016/hello_go
    username:
      from_secret: docker_un
    password:
      from_secret: docker_pw
